rust-lang/atom-ide-rust

README.md, lib/index.js
The rls component has been [renamed to rls-preview](https://github.com/rust-lang-nursery/rls/blob/master/README.md#step-3-install-the-rls).
=> Change rls -> rls-preview, use stable toolchain

README.md, lib/index.js
Despite installing and appearing to run correctly, rls-preview doesn't work on stable despite being 1.21. I think we should just revert my commit from yesterday until that changes. Very sorry for not realizing the issues before creating the PR, my fault.
This reverts commit dd3722dbebaa541d4361f05abdc7d19e00ea5834.
Fixes #10
=> Revert "Use default toolchain if present, stable otherwise"

README.md, lib/index.js, lib/rls-project.js, package-lock.json, package.json
We will now watch `rls.toml` files in the project roots, if present on open or changed we'll send *DidChangeConfiguration* messages to rls derived from the contents.
After all that I found rls workspaces didn't work for me anyway, presumably as they're still a work in progress. But I think being able to config rls in this way is a useful addition in any case.
I added `lodash` and `toml` dependency. The former isn't *heavily* used, so if you have a different preference it'll be easy to change. I tried to adopt your *no-semi-colons-allowed* style, which felt wrong. I had to delete many semi colons I couldn't prevent myself from typing.
Resolves  #13
=> Add Rls configuration using project `rls.toml` files

lib/index.js, lib/rls-project.js
**tl;dr** The changes in this PR are required for this package to be usable on my machine.
Currently, if you enable logging on `atom-languageclient` via `atom.config.set('core.debugLSP', true)` and reload, this is what you see on startup.
It seems that we're getting into an endless loop. We detect the language server's own changes writing to a subdirectory of the project's `target` folder, then send those changes to the language server, which triggers another build and more writes, etc...
This PR makes use of the `filterChangeWatchedFiles` hook to avoid reporting changes inside of this `target` folder or the `.git` directory. It also takes care of updating the `rls.toml` while we're at it to avoid the need to subscribe to changes on package activation.
I also took some care to optimize …
=> Urgent fix: Use filterChangeWatchedFiles hook to avoid infinite change loop

lib/index.js, package-lock.json, package.json
By taking advantage of the new `filterChangeWatchedFiles` method in atom-languageclient:0.6.6 we can solve the immediate watch-message spam issue by ignoring target/rls & .git files.
Actually rls is expecting an `initialized` notification, to which it will request `client/registerCapability` telling us which files we should watch. So ideally we should filter out ***all*** didChangeWatchedFiles until we've received which files are required (currently just Cargo.toml, Cargo.lock and target/).
However, since sending a `initialized` notification & handling `client/registerCapability` requests are currently not in atom-languageclient I think its best to put a plaster on this for now (with a healthy *TODO*) and tackle handling that stuff later.
=> Use filterChangeWatchedFiles to reduce watch message spam

lib/index.js
This PR adds some messaging for rls installation failures, and allows configuring the desired rls toolchain.
For example, when current nightly is missing rls:
Summary
* Add user messages for toolchain installation failures
* Use simpler method to check toolchain is installed
* Allow setting the rust toolchain in package config
Note it seems we can't restart rls when the config changes, so in some cases atom will need to be restarted. Hopefully this will change upstream, see https://github.com/atom/atom-languageclient/issues/135.
Mostly resolves #16
=> Configurable rls toolchain

README.md, lib/index.js
This PR allows overriding the Rls exec command. This is really useful if you're troubleshooting or developing the Rls. For example I'm using it to test my local Rls changes.
Initially it has to be added to config.cson manually, this is because this option _shouldn't_ be of interest to most users. Note: Once you have added something to config.cson you'll be able to edit/remove it from the ide-rust settings menu.
Built on top of / includes #20.
The Rls command can be specified manually, for example to run from local source code:
```cson
...
"ide-rust":
rlsCommandOverride: "rustup run nightly cargo run --manifest-path=/rls-src/Cargo.toml --release"
```
When set you'll be able to see, and remove, this from the package settings. After restarting atom an info message will inform you the …
=> Rls command override

package.json
With respect to other Atom IDE packages such as [ide-java](https://github.com/atom/ide-java/blob/master/package.json#L5) or [ide-php](https://github.com/atom/ide-php/blob/master/package.json#L5). The fact that this plugin uses the RLS in the backend is an implementation detail.
=> Normalize the package description

lib/index.js, package-lock.json, package.json
This change adds _atom-ide-busy-signal_ service support.
* Replaces `Installing rust...` notification with busy signal
* Adds busy signal for `Adding components rls-preview, rust-src, rust-analysis` (previously not notified)
* Also adds a **Reload** button to `Switched Rls toolchain to...` notification _(will do the same as ctrl-shift-F5)_
=> Add busySignal support + window:reload button on toolchain change

lib/index.js, lib/rls-project.js, package-lock.json, package.json
Commit 26da404f669f2eba60f3dff5b2e4d97443cb88a5 (on top of #25, #24) updates to latest upstream client + uses the busySignalService injected there. 
This means we have busy-signal coverage for 
- installation
- server startup _(upstream)_
- server rustc building
- server shutdown  _(upstream)_
=> Update atom-languageclient to 0.7.0 + use upstream shared busySignalService

lib/index.js, package-lock.json
* Propogate error when rls is not found
* Don't check toolchain/rls when `rlsCommandOverride` is present.
Currently server startup can return a non failing promise when Rls is missing, despite showing the correct error notification. This can cause atom-languageclient to show busy-signal 'initializing' without end, which is how I noticed it.
I also removed the toolchain/rls check when using `rlsCommandOverride` and simplified this branch of the code.
=> Propogate error when rls is not found

lib/index.js
Prevents masses of watched file change messages when building debug/release while Rls is running.
These aren't a huge problem as Rls ignores them, but still worth making a small addition to ignore them as they still spam the logs.
=> Add filter watch ignores for target/debug & target/release

README.md, lib/index.js, package-lock.json, package.json
This pr adds a check for available updates to the selected rust/rls toolchain on startup.
When available a prompt will allow updating
* Toolchain updating
* Check for toolchain update at startup
* Check for toolchain update after switching toolchain
* Only prompts to update if update has _'rls-preview'_
* Skips check if toolchain is dated _(e.g. nightly-2017-12-12)_
* Enabled/disable in settings _(default enabled)_
* Chang _'switched toolchain'_ prompt to a _success_ style one
* Add toolchain update info to readme features
* Add 'other packages not required' note to readme _Install_ section
Resolves #30
=> Add toolchain update checking on startup

lib/index.js, package-lock.json, package.json
Update to atom-languageclient 0.8.1 allows programmatic server restart, so we can simply notify users after switching toolchain instead of having to reload atom. 
https://github.com/atom/atom-languageclient/pull/171 fixes #39
=> Automatically restart language servers on toolchain change

.eslintrc.js, README.md, lib/dist-fetch.js, lib/index.js, lib/rls-project.js, package-lock.json, package.json
This pr enhances toolchain handling particularly to more gracefully deal with the lack of Rls in some nightlies.
- Graceful handling of Rls being missing from the distribution
* Warns before installing a rust version without Rls or when using an already installed one
* Automatic detection of, and prompt to install, the latest working dated release
- Updates from dated toolchains are now enabled
- Checks for toolchain updates every 6 hours
- Checks for toolchain updates when enabling the _check for toolchain updates_ setting
- Some language server startup issues were fixed in atom-languageclient `0.8.2`
- Added jsdoc to the eslint list and tweaked the rules a little more
Initial startup experience using default `nightly` toolchain, but when the current nightly release is missing Rls.
This …
=> Toolchain handling II

lib/index.js
This pr uses `rustc --print sysroot` to find the sysroot rather than toolchain name itself. This should help racer to work regardless of toolchain choice.
=> Set RUST_SRC_PATH correctly for dated toolchains

lib/index.js
* Add rls env: RUST_BACKTRACE=1
* Add rls env: RUST_LOG=atom_process.env.RUST_LOG
* When core.debugLSP add rls env: RUST_LOG=rls=warn (if not already set)
* Avoid concurrent checkRls promises _(can cause update error messages)_
* Don't use parent process RUST_SRC_PATH, it's unlikely to be correct for a dated toolchain
=> Improve rls console logging

lib/rls-project.js, package-lock.json, package.json
=> Support Rls window/progress messages

README.md, lib/index.js, lib/rls-project.js
This pr brings the idea of global default Rls config that can be centrally modified. ~It also brings a change to the default behaviour as `all_targets` will be set to true by default. That's because I think test & example code should be checked by Rls by default, even though that isn't the case currently upstream.~ I changed my mind and instead the default will be the same as before - upstream Rls defaults.
* Add global `all_targets` Rls config
* Defer initial toolchain update check until first Rls startup. This reduces package startup time + means you don't have to deal with rust toolchain updates if you're using atom for something other than rust (heaven forbid). This brings the startup time down to around ~60ms.
* Sort settings
=> Add customisable global Rls config + defer update checking

lib/index.js
This commit in combination with the [changes in RLS categorization](https://github.com/rust-lang-nursery/rls/pull/734) make the outline view more useful and fixes #58.  
These are three outlines for the RLS's [rustc.rs](https://github.com/rust-lang-nursery/rls/blob/master/src/build/rustc.rs) file. The first is the previous state where there are many local variables between methods, the second one just filters the local variables in RLS and the third uses the new categorization and filter variables on ide-rust. Notice methods and fields are now properly shown.
=> Test code provided by alexheretic to filter variable type

lib/index.js
Atom has [added](https://github.com/atom/atom/pull/16299) experimental support for a new parsing system called [Tree-sitter](https://github.com/tree-sitter/tree-sitter). There is a [rust parser](https://github.com/tree-sitter/tree-sitter-rust) for Tree-sitter and a new [Atom package](https://github.com/atom/language-rust) that uses that parser.
The Tree-sitter grammars use a different convention for scope names than the TextMate grammars. Language names are no longer abbreviated by "source.". This PR adds the simple scope name `rust` to the list of scopes that this package supports, so that we can use this package when editing rust code with Tree-sitter enabled.
=> Add plain `rust` as an additional grammar scope

lib/index.js
* Include process.env in rls env
* Add windows env.path implementation
* Use process.env RUST_BACKTRACE if available
=> Fix Windows link.exe not found

lib/index.js
Adds new setting to disable ide-rust on certain projects.
The implementation to return a null-promise is a bit crude, but I can see a better option and this does the job with minimal code - easy to improve later.
Resolves #87
=> Add ignoredProjectPaths setting

lib/index.js
This may help #89, but also makes sense to execute rustup in the same way in all cases.
=> Include process.env in rustup execution env

lib/dist-fetch.js
Today's nightly does not include rls, but the manifest format has changed so that the check that the manifest contains `rls-preview` no longer works.
Now the manifest has
```
...
[pkg.rls-preview]
version = ""
[pkg.rls-preview.target.aarch64-unknown-linux-gnu]
available = false
[pkg.rls-preview.target.arm-unknown-linux-gnueabi]
available = false
[pkg.rls-preview.target.arm-unknown-linux-gnueabihf]
available = false
[pkg.rls-preview.target.armv7-unknown-linux-gnueabihf]
available = false
[pkg.rls-preview.target.i686-apple-darwin]
available = false
[pkg.rls-preview.target.i686-pc-windows-gnu]
available = false
...
```
This change requires the manifest contain rls, and **not** contain `[pkg.rls-preview]\nversion = ""`.  This works for the moment, and is backward compatible with the old …
=> Fix dated nightly search

README.md
This PR adds more explicit documentation for how to handle Atom projects that have Rust crates nested within the project (i.e. not at the root of the project). The multi-crate documentation already provided instructions on how to handle this case, but it was not immediately clear to me that the instructions still applied to a project with only one non-root crate. This addition should make it easier for new users to figure out what they need to do, or at least easier to point them in the right direction when they have questions.
Resolves #100
=> Add more explicit documentation for non-root crates

lib/index.js
Shows build time info in console when `atom.config.set('core.debugLSP', true)`
Introduced to rls in https://github.com/rust-lang-nursery/rls/pull/1072, so should soon be in future releases.
=> Default add rls::build=info to RUST_LOG

lib/index.js
Replace "unavilable" with "unavailable." Also capitalized RLS in this message.
ide-rust is great!
=> Typo fix in warning message for unavailable toolchain

package.json
Built-in support for Rust syntax is amazing thanks to tree-sitter
=> Remove language-rust as a package dependency

lib/index.js
Fixes #114 
Better support for no-rustup envs should come later, see #115
=> Avoid notifying about rlsCommandOverride being 'rls'

lib/index.js, lib/rls-project.js
This pr eases the current issues with multi-crate projects by offering workarounds with minimum effort.
```
rls-1202/
├── project-bar
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── project-foo
├── Cargo.toml
└── src
└── lib.rs
```
If you open _rls-1202_ as a project in atom RLS will fail to find the root manifest and won't work.
A decent workaround it to add a root workspace manifest. 
```toml
[workspace]
members = ["project-bar", "project-foo"]
```
With this RLS can work compiling everything and using a single root `./target` directory.
You may also want to ignore the project and do without RLS functionality. This PR adds both workarounds as clickable actions when it can detect them.
Resolves #69
=> Multi crate workaround dialog

lib/index.js, package-lock.json, package.json
I've proposed [support for out-of-project files upstream](https://github.com/atom/atom-languageclient/pull/253). This provides language server support for cargo dependencies and the std library.
With the state of atom-languageclient I assume this will rest unmerged for the foreseeable future so ide-rust will now use a fork: `alexheretic/atom-languageclient#build`
Fixes #96
=> Support out-of-project files

lib/index.js
Switch to the stable toolchain by default with the 1.34 release.
Resolves #128
=> Switch to stable toolchain by default

lib/index.js, package-lock.json, package.json
This change switches the default toolchain to `''` which will now mean "use rustup/system default toolchain". This allows rustup overrides to be used.
Closes #135
=> Support use of rustup default toolchain & overrides

lib/index.js
This change allows ide-rust to be used without rustup. The toolchain should be set to `''` which is the new default. Note: Update checking isn't supported without rustup.
Closes #115
=> Support rustup-less environments

lib/index.js, package-lock.json
Rls is fine with being killed and quick kills provide a nicer experience.
Required upstream changes (now included in fork): https://github.com/atom/atom-languageclient/pull/269
Closes #134
=> Kill rls processes instead of awaiting shutdown

README.md, lib/competition.js, lib/index.js, lib/rls-project.js, lib/rust-project.js, package-lock.json, package.json
=> Switch from RLS to rust-analyzer

package-lock.json
=> Update atom-languageclient to use rimraf for building

snippets/rust.cson
Thanks for maintaining this plugin! I'm the person who added the snippets in #112.
Rust has added many new features since those snippets were first created in the `language-rust` plugin. We now have `eprint` and `eprintln` for printing to stderr, and `todo` as a substitute for `unimplemented`. I added snippets for each of those and for `unreachable`/`unimplemented` as well since both of those are very useful. 
The snippets in the file are in alphabetical order, so I made my changes to keep that consistent.
These are snippets I've had in my snippets file for a while and I hope others will find them as useful as I have. :)
=> Add snippets for eprint, eprintln, todo, unimplemented, and unreachable

lib/index.js
Convert rust-analyzer datatip/hover responses ```` ```rust\ncode\n``` ```` into text & rust-snippets of `code` to allow syntax highlighting of these snippets.
This presumably is a flaw in atom-ide-ui not highlighting markdown.
Remove old rls format workaround.
Resolves #158
=> Workaround missing markdown syntax highlighting

lib/index.js
=> Improve the missing rust-analyzer bin error notification

lib/index.js, package-lock.json
In my updated atom-languageclient fork I've added the ability to filter & to custom handle codeActions. In this PR we'll start supporting the more standard / simple code actions.
The custom `rust-analyzer.applySourceChange` actions are not yet supported (and so not offered) but we now have a scaffold to implement custom handling in future using `onApplyCodeActions`.
=> Support some standard code actions, filter out rust-analyzer custom ones

lib/index.js
=> fix: kill rust-analyzer fast without waiting for the close response from

lib/index.js
Allow a user to configure the rust-analyzer server with a config file similar to the previously used `rls.toml`.
Closes #166
=> Configure rust-analyzer with project-specific config files

.github/workflows/CI.yml
Each job currently produces its own warning, resulting in 4 identical warnings. It seems redundant to include the lint step in the test CI jobs.
=> Remove duplicate lint warnings

README.md, lib/index.js
Thanks for your help with the addition of the config file. I based it off how the `rls.toml` file used to work, where the file was found in the root directory of the project. However, I think it would be better to store config files in a hidden directory, similar to how VSCode does.
=> Move config files to avoid cluttering project root

README.md
Adds an example configuration to use the nightly toolchain when formatting.
=> Add `cargo +nightly fmt` example to readme

lib/index.js, lib/rust-project.js
Removes unused code related to old `rls.toml` config files.
=> Remove unused `rls.toml` code

.github/workflows/CI.yml
Changes the name from `ubuntu-latest - Atom` to `ubuntu-latest - Lint`
=> Change the lint CI job name to be more descriptive

lib/index.js
The datatips shown on hover were just showing malformed plaintext documentation rather than rendered markdown. This should fix it.
=> Fixed markdown in datatips
